//! `SeaORM` Entity. Generated by sea-orm-codegen 0.10.5
use async_graphql::SimpleObject;
use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, SimpleObject)]
#[sea_orm(table_name = "Persona")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(column_name = "createdAt")]
    pub created_at: DateTime,
    #[sea_orm(unique)]
    pub name: String,
    #[sea_orm(column_name = "screenName")]
    pub screen_name: String,
    #[sea_orm(column_name = "iconUrl", column_type = "Text")]
    pub icon_url: String,
    #[sea_orm(column_name = "userId")]
    pub user_id: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
