//! `SeaORM` Entity. Generated by sea-orm-codegen 0.10.5

use async_graphql::Enum;
use sea_orm::entity::prelude::*;
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Enum, Copy)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "contentType")]
pub enum ContentType {
    #[sea_orm(string_value = "TEXT")]
    Text,
    #[sea_orm(string_value = "LINK")]
    Link,
    #[sea_orm(string_value = "IMAGE")]
    Image,
    #[sea_orm(string_value = "VIDEO")]
    Video,
    #[sea_orm(string_value = "EMOJI")]
    Emoji,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Enum, Copy)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "type")]
pub enum Type {
    #[sea_orm(string_value = "BOT")]
    Bot,
    #[sea_orm(string_value = "USER")]
    User,
}
