//! `SeaORM` Entity. Generated by sea-orm-codegen 0.10.5

pub mod prelude;

pub mod allowed_writing_role;
pub mod board;
pub mod board_role;
pub mod bot;
pub mod following_board;
pub mod notification_event;
pub mod persona;
pub mod persona_relation;
pub mod post;
pub mod post_role;
pub mod reply;
pub mod sea_orm_active_enums;
pub mod system_administrator_role;
pub mod third_party_api_key;
pub mod thread;
pub mod uploaded_image;
pub mod user;
pub mod vote_on_comment;
pub mod vote_on_post;
