//! `SeaORM` Entity. Generated by sea-orm-codegen 0.10.6

pub use super::board::Entity as Board;
pub use super::bot::Entity as Bot;
pub use super::persona::Entity as Persona;
pub use super::post::Entity as Post;
pub use super::reply::Entity as Reply;
pub use super::thread::Entity as Thread;
pub use super::user::Entity as User;
