//! `SeaORM` Entity. Generated by sea-orm-codegen 0.10.5

pub use super::allowed_writing_role::Entity as AllowedWritingRole;
pub use super::board::Entity as Board;
pub use super::board_role::Entity as BoardRole;
pub use super::bot::Entity as Bot;
pub use super::following_board::Entity as FollowingBoard;
pub use super::notification_event::Entity as NotificationEvent;
pub use super::persona::Entity as Persona;
pub use super::persona_relation::Entity as PersonaRelation;
pub use super::post::Entity as Post;
pub use super::post_role::Entity as PostRole;
pub use super::reply::Entity as Reply;
pub use super::system_administrator_role::Entity as SystemAdministratorRole;
pub use super::third_party_api_key::Entity as ThirdPartyApiKey;
pub use super::thread::Entity as Thread;
pub use super::uploaded_image::Entity as UploadedImage;
pub use super::user::Entity as User;
pub use super::vote_on_comment::Entity as VoteOnComment;
pub use super::vote_on_post::Entity as VoteOnPost;
